BEGIN TRANSACTION;
insert into products (name,price,description,image_url)
VALUES
    ('Cally Saunders',50.99,'Nunc lectus pede, ultrices a, auctor non,','https://whatsapp.com'),
    ('Derek Farrell',14.82,'tristique neque venenatis','http://youtube.com'),
    ('Ignatius Barrera',19.34,'feugiat placerat velit. Quisque varius. Nam porttitor scelerisque','https://walmart.com'),
    ('Knox Mendoza',26.85,'risus a ultricies adipiscing, enim mi','https://twitter.com'),
    ('Zeph Burke',43.41,'congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante','http://ebay.com'),
    ('Keaton Cantu',26.32,'vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo.','https://instagram.com'),
    ('Patricia Norton',14.17,'amet, consectetuer adipiscing elit. Aliquam auctor, velit eget','http://netflix.com'),
    ('Wylie Conley',80.59,'elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet','http://ebay.com'),
    ('Byron Madden',69.33,'magna. Suspendisse tristique neque venenatis lacus.','https://baidu.com'),
    ('Hedy Hamilton',94.37,'orci, consectetuer euismod est','http://netflix.com'),
    ('Dominique Williams',83.58,'elit fermentum risus, at','https://ebay.com'),
    ('Maia Rodriquez',25.32,'scelerisque dui. Suspendisse ac metus','http://naver.com'),
    ('Ora Farmer',91.21,'Phasellus dolor elit, pellentesque','http://pinterest.com'),
    ('Omar Hensley',38.93,'rutrum eu,','https://walmart.com'),
    ('Petra Cooley',82.28,'ad litora','https://nytimes.com'),
    ('Mari Schroeder',70.05,'consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna.','https://twitter.com'),
    ('Colleen Landry',95.42,'fringilla','http://walmart.com'),
    ('Raymond Small',37.95,'auctor. Mauris vel turpis. Aliquam','http://youtube.com'),
    ('Travis Fowler',98.98,'enim. Mauris quis turpis vitae purus gravida','http://netflix.com'),
    ('Russell Tillman',76.85,'molestie pharetra nibh.','http://reddit.com'),
    ('Abigail Walker',55.05,'fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas','http://instagram.com'),
    ('Audrey Gamble',18.81,'facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed','http://guardian.co.uk'),
    ('Maxwell Bray',26.14,'ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum','http://bbc.co.uk'),
    ('Zenaida King',99.73,'amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut','https://zoom.us'),
    ('Ebony Mcclain',31.87,'a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet,','https://wikipedia.org'),
    ('Kim Watson',94.38,'gravida molestie arcu. Sed','https://naver.com'),
    ('Grace Burton',0.84,'montes, nascetur ridiculus mus. Proin vel arcu eu','https://baidu.com'),
    ('Ella Walton',91.80,'purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum','http://cnn.com'),
    ('Shaeleigh Gilliam',27.33,'in lobortis tellus justo sit amet nulla. Donec non','http://reddit.com'),
    ('Kadeem Russo',50.83,'Donec luctus aliquet odio. Etiam ligula tortor,','http://instagram.com'),
    ('Jonas Charles',14.33,'justo. Praesent luctus. Curabitur egestas nunc sed libero. Proin','https://zoom.us'),
    ('Rebekah Spence',69.83,'Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor.','http://youtube.com'),
    ('Jael Guy',24.87,'lectus. Cum sociis natoque','http://yahoo.com'),
    ('Avye Hendrix',36.77,'gravida','http://cnn.com'),
    ('Stuart Frye',80.58,'varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In','http://twitter.com'),
    ('Calvin Bates',9.65,'sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor,','http://zoom.us'),
    ('Maggie Gill',57.83,'ipsum ac mi eleifend egestas. Sed pharetra,','https://naver.com'),
    ('Eagan Jacobs',41.38,'Ut nec urna et','http://baidu.com'),
    ('Elizabeth Maxwell',1.42,'vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu','http://cnn.com'),
    ('Lynn Velazquez',45.04,'Phasellus dolor elit,','https://youtube.com'),
    ('Kasper Mays',3.11,'sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat','https://guardian.co.uk'),
    ('Travis Clay',95.12,'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus','http://whatsapp.com'),
    ('Kitra Turner',52.81,'mauris eu elit. Nulla facilisi. Sed','https://yahoo.com'),
    ('Judah Bullock',4.83,'enim diam vel','https://netflix.com'),
    ('Gary May',6.25,'Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum','http://cnn.com'),
    ('Brynn Mosley',12.85,'ante. Nunc mauris sapien, cursus in,','https://walmart.com'),
    ('Magee Bean',65.66,'iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus','http://bbc.co.uk'),
    ('Gay Harding',8.05,'quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.','http://youtube.com'),
    ('Samuel Decker',38.52,'facilisi. Sed neque. Sed eget lacus. Mauris non dui','https://bbc.co.uk'),
    ('Harriet Hewitt',94.20,'porta elit,','https://walmart.com');
COMMIT;